Transform: AWS::Serverless-2016-10-31

Description: Stack per il deploy dell'api gateway per interagire con i dispositivi

Globals:
  Function:
    Timeout: 5
    MemorySize: 256
    Environment:
      Variables:
        AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        MainTable: !Ref MainTable

Parameters: {}

Resources:
  API: # the api responsible for publishing methods
    Type: AWS::Serverless::Api
    Properties:
      Description: API per la gestione dei dispositivi
      EndpointConfiguration:
        Type: EDGE
      MinimumCompressionSize: 0
      OpenApiVersion: "3.0.1"
      StageName: api
      TracingEnabled: true

  GreetingsFn: # the function to fullfil API requests
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/python38/greetings/greetings
      Handler: main.handler
      Runtime: python3.8
      Description: Greetings function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /python38/greetings
            Method: GET

  GreetingsGoFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/go/greetings
      Handler: main
      Runtime: go1.x
      Description: Greetings Go function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /go/greetings
            Method: GET

  GreetingsJavaFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/java/greetings-jvm.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Description: Greetings Java function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /quarkus/java/greetings
            Method: GET

  GreetingsJavaNativeFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/java/greetings-native.zip
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Description: Greetings Java Native function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /quarkus/native/greetings
            Method: GET


  DivisorsFn: # the function to fullfil API requests
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/python38/divisors/divisors
      Handler: main.handler
      Runtime: python3.8
      Description: Greetings function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /python38/numbers/{n}/divisors
            Method: GET

  DivisorsGoFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/go/divisors
      Handler: main
      Runtime: go1.x
      Description: Divisors Go function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /go/numbers/{n}/divisors
            Method: GET

  DivisorsJavaFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/java/divisors-jvm.zip
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      Description: Divisors Java function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /quarkus/java/numbers/{n}/divisors
            Method: GET

  DivisorsJavaNativeFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/java/divisors-native.zip
      Handler: not.used.in.provided.runtime
      Runtime: provided
      Description: Divisors Java Native function for Cloud Benchmark
      Tracing: PassThrough
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /quarkus/native/numbers/{n}/divisors
            Method: GET

  MainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  DySinglePyFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/python38/dysingle/dysingle
      Handler: main.handler
      Runtime: python3.8
      Description: DynamoDB Single function for Cloud Benchmark
      Tracing: PassThrough
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MainTable
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /python38/dynamo/single/{key}
            Method: GET

  DySingleGoFn:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      CodeUri: ./lambda/go/dysingle
      Handler: main
      Runtime: go1.x
      Description: DynamoDB Single function for Cloud Benchmark
      Tracing: PassThrough
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MainTable
      Events:
        PostCommand:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /go/dynamo/single/{key}
            Method: GET
